server:
  port: 9001
spring:
  application:
    name: rabbitmq-provider
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: admin
    password: admin
    #虚拟host，可以不设置，使用server默认host
    virtual-host: my_vhost

    #消息确认配置项
    ##确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    ##确认消息已发送到队列(Queue)
    publisher-returns: true
